/**
 * AUTO-GENERATED BY scripts/frontend-api-code-generator/gen.py
 */
import qs from "qs";
import request from "@/utils/request";

const api = {
  loginAccessToken: data => {
    return request({
      url: "/login/access-token",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      },
      data: qs.stringify(data),
      method: "post"
    });
  },
  testToken: data => {
    return request({
      url: "/login/test-token",
      data: data,
      method: "post"
    });
  },
  resetPassword: data => {
    return request({
      url: "/reset-password/",
      headers: {
        "Content-Type": "application/json"
      },
      data: data,
      method: "post"
    });
  }
};
export default api;
