/**
 * AUTO-GENERATED BY scripts/frontend-api-code-generator/gen.py
 */
import request from "@/utils/request";

const api = {
  readPermissions: params => {
    return request({
      url: "/permissions/",
      params: params,
      method: "get"
    });
  },
  createPermission: data => {
    return request({
      url: "/permissions/",
      headers: {
        "Content-Type": "application/json"
      },
      data: data,
      method: "post"
    });
  },
  readPermissionByCode: (code, params) => {
    return request({
      url: "/permissions/" + code,
      params: params,
      method: "get"
    });
  },
  updatePermission: (code, data) => {
    return request({
      url: "/permissions/" + code,
      headers: {
        "Content-Type": "application/json"
      },
      data: data,
      method: "put"
    });
  },
  deletePermission: code => {
    return request({
      url: "/permissions/" + code,
      method: "delete"
    });
  }
};
export default api;
