/**
 * AUTO-GENERATED BY scripts/frontend-api-code-generator/gen.py
 */
import request from "@/utils/request";

const api = {
  readUsers: params => {
    return request({
      url: "/users/",
      params: params,
      method: "get"
    });
  },
  createUser: data => {
    return request({
      url: "/users/",
      headers: {
        "Content-Type": "application/json"
      },
      data: data,
      method: "post"
    });
  },
  readUserMe: params => {
    return request({
      url: "/users/me",
      params: params,
      method: "get"
    });
  },
  updateUserMe: data => {
    return request({
      url: "/users/me",
      headers: {
        "Content-Type": "application/json"
      },
      data: data,
      method: "put"
    });
  },
  readUserById: (user_id, params) => {
    return request({
      url: "/users/" + user_id,
      params: params,
      method: "get"
    });
  },
  updateUser: (user_id, data) => {
    return request({
      url: "/users/" + user_id,
      headers: {
        "Content-Type": "application/json"
      },
      data: data,
      method: "put"
    });
  }
};
export default api;
