"""permission code 255

Revision ID: 3f93e807d29a
Revises: 4775152b8453
Create Date: 2021-03-22 15:43:10.311585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f93e807d29a'
down_revision = '4775152b8453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
