"""add user/role/permission

Revision ID: 8c6ab85930f3
Revises: 
Create Date: 2021-03-04 18:19:37.431132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c6ab85930f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_permission',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('conf', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_sys_permission_code'), 'sys_permission', ['code'], unique=False)
    op.create_table('sys_role_permission_rel',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('role_id', 'permission_code')
    )
    op.create_index(op.f('ix_sys_role_permission_rel_role_id'), 'sys_role_permission_rel', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_role_permission_rel_role_id'), table_name='sys_role_permission_rel')
    op.drop_table('sys_role_permission_rel')
    op.drop_index(op.f('ix_sys_permission_code'), table_name='sys_permission')
    op.drop_table('sys_permission')
    # ### end Alembic commands ###
