"""add email field

Revision ID: bbcb142b0297
Revises: db4e825405dc
Create Date: 2021-03-01 17:21:22.633537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcb142b0297'
down_revision = 'db4e825405dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_user', sa.Column('email', sa.String(), nullable=False))
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_column('sys_user', 'email')
    # ### end Alembic commands ###
